In [1]:
import pandas as pd
import numpy as np
from LVQ import LVQ
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [2]:
colnames = ['Sample_code_number', 'Clump_Thickness', 'Uniformity_of_Cell_Size', 'Uniformity_of_Cell_Shape',
            'Marginal_Adhesion', 'Single_Epithelial_Cell_Size', 'Bare_Nuclei', 'Bland_Chromatin',
            'Normal_Nucleoli', 'Mitoses', 'Class']
data = pd.read_csv("breast-cancer-wisconsin.data", names=colnames)
data.head()

,Sample_code_number,Clump_Thickness,Uniformity_of_Cell_Size,Uniformity_of_Cell_Shape,Marginal_Adhesion,Single_Epithelial_Cell_Size,Bare_Nuclei,Bland_Chromatin,Normal_Nucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2

In [3]:

# Data pre processing
data = data.replace({'Class': {2: "Benign", 4: "Malignant"}})
# Replacing the missing values with 1
# data = data.replace({'?': 1})
# Remove data wich has missing values
data = data[data.Bare_Nuclei != "?"]

total_samples = data['Sample_code_number'].count()
print("Number of rows\t: {}".format(total_samples))
cat_vars = ['Clump_Thickness', 'Uniformity_of_Cell_Size', 'Uniformity_of_Cell_Shape',
                    'Marginal_Adhesion', 'Single_Epithelial_Cell_Size', 'Bare_Nuclei', 'Bland_Chromatin',
                    'Normal_Nucleoli', 'Mitoses', 'Class']
data_final = data[cat_vars]

Number of rows	: 683

In [4]:
data_final.isnull().sum()

Clump_Thickness                0
Uniformity_of_Cell_Size        0
Uniformity_of_Cell_Shape       0
Marginal_Adhesion              0
Single_Epithelial_Cell_Size    0
Bare_Nuclei                    0
Bland_Chromatin                0
Normal_Nucleoli                0
Mitoses                        0
Class                          0
dtype: int64

In [5]:
data_final['Class'].nunique()

2

In [6]:
# data_final["Bare_Nuclei"] = data_final.to_numeric(df["Bare_Nuclei"])
data_final = data_final.astype({"Bare_Nuclei": int})
data_final.head()

,Clump_Thickness,Uniformity_of_Cell_Size,Uniformity_of_Cell_Shape,Marginal_Adhesion,Single_Epithelial_Cell_Size,Bare_Nuclei,Bland_Chromatin,Normal_Nucleoli,Mitoses,Class
0,5,1,1,1,2,1,3,1,1,Benign
1,5,4,4,5,7,10,3,2,1,Benign
2,3,1,1,1,2,2,3,1,1,Benign
3,6,8,8,1,3,4,3,7,1,Benign
4,4,1,1,3,2,1,3,1,1,Benign

In [7]:
# col_names = data_final.columns
# from sklearn import preprocessing
# min_max_scaler = preprocessing.MinMaxScaler()
# scaled_dataframe = data_final.iloc[:, :-1]
# # print(scaled_dataframe.head())
# np_scaled = min_max_scaler.fit_transform(scaled_dataframe)
# df_scale = pd.DataFrame(np_scaled, columns=col_names[:-1])
# frames = [df_scale, data_final.iloc[:, -1]]
# result = pd.concat(frames, axis=1)
# result.head()

In [13]:
# LVQ
obj = LVQ()
reduced_data = obj.fit(data_final, 500, 0.3, 100, normalize=False)

>epoch=0, lrate=0.300, error=7614.649
>epoch=1, lrate=0.297, error=7506.475
>epoch=2, lrate=0.294, error=7084.430
>epoch=3, lrate=0.291, error=6471.083
>epoch=4, lrate=0.288, error=6158.788
>epoch=5, lrate=0.285, error=5862.694
>epoch=6, lrate=0.282, error=5643.074
>epoch=7, lrate=0.279, error=5592.361
>epoch=8, lrate=0.276, error=5597.942
>epoch=9, lrate=0.273, error=5634.625
>epoch=10, lrate=0.270, error=5524.763
>epoch=11, lrate=0.267, error=5493.201
>epoch=12, lrate=0.264, error=5512.912
>epoch=13, lrate=0.261, error=5394.562
>epoch=14, lrate=0.258, error=5458.473
>epoch=15, lrate=0.255, error=5442.027
>epoch=16, lrate=0.252, error=5329.265
>epoch=17, lrate=0.249, error=5456.333
>epoch=18, lrate=0.246, error=5402.558
>epoch=19, lrate=0.243, error=5368.247
>epoch=20, lrate=0.240, error=5339.579
>epoch=21, lrate=0.237, error=5345.022
>epoch=22, lrate=0.234, error=5333.432
>epoch=23, lrate=0.231, error=5339.173
>epoch=24, lrate=0.228, error=5307.173
>epoch=25, lrate=0.225, error=5322.681
>epoch=26, lrate=0.222, error=5217.362
>epoch=27, lrate=0.219, error=5328.160
>epoch=28, lrate=0.216, error=5227.281
>epoch=29, lrate=0.213, error=5255.431
>epoch=30, lrate=0.210, error=5236.088
>epoch=31, lrate=0.207, error=5212.604
>epoch=32, lrate=0.204, error=5146.093
>epoch=33, lrate=0.201, error=5180.738
>epoch=34, lrate=0.198, error=5190.530
>epoch=35, lrate=0.195, error=5160.225
>epoch=36, lrate=0.192, error=5132.590
>epoch=37, lrate=0.189, error=5137.363
>epoch=38, lrate=0.186, error=5164.985
>epoch=39, lrate=0.183, error=5159.185
>epoch=40, lrate=0.180, error=5070.349
>epoch=41, lrate=0.177, error=5103.951
>epoch=42, lrate=0.174, error=5085.034
>epoch=43, lrate=0.171, error=5057.915
>epoch=44, lrate=0.168, error=5055.907
>epoch=45, lrate=0.165, error=5019.173
>epoch=46, lrate=0.162, error=5060.663
>epoch=47, lrate=0.159, error=5058.003
>epoch=48, lrate=0.156, error=4982.637
>epoch=49, lrate=0.153, error=5032.465
>epoch=50, lrate=0.150, error=4998.323
>epoch=51, lrate=0.147, error=4988.246
>epoch=52, lrate=0.144, error=5002.362
>epoch=53, lrate=0.141, error=4962.577
>epoch=54, lrate=0.138, error=4922.157
>epoch=55, lrate=0.135, error=4947.268
>epoch=56, lrate=0.132, error=4951.456
>epoch=57, lrate=0.129, error=4875.388
>epoch=58, lrate=0.126, error=4928.666
>epoch=59, lrate=0.123, error=4908.423
>epoch=60, lrate=0.120, error=4870.023
>epoch=61, lrate=0.117, error=4864.019
>epoch=62, lrate=0.114, error=4823.329
>epoch=63, lrate=0.111, error=4805.480
>epoch=64, lrate=0.108, error=4840.268
>epoch=65, lrate=0.105, error=4823.073
>epoch=66, lrate=0.102, error=4780.452
>epoch=67, lrate=0.099, error=4793.319
>epoch=68, lrate=0.096, error=4780.158
>epoch=69, lrate=0.093, error=4739.051
>epoch=70, lrate=0.090, error=4752.850
>epoch=71, lrate=0.087, error=4741.033
>epoch=72, lrate=0.084, error=4675.767
>epoch=73, lrate=0.081, error=4697.560
>epoch=74, lrate=0.078, error=4679.127
>epoch=75, lrate=0.075, error=4691.241
>epoch=76, lrate=0.072, error=4649.908
>epoch=77, lrate=0.069, error=4631.950
>epoch=78, lrate=0.066, error=4653.100
>epoch=79, lrate=0.063, error=4636.180
>epoch=80, lrate=0.060, error=4624.435
>epoch=81, lrate=0.057, error=4608.557
>epoch=82, lrate=0.054, error=4596.609
>epoch=83, lrate=0.051, error=4555.346
>epoch=84, lrate=0.048, error=4539.103
>epoch=85, lrate=0.045, error=4558.227
>epoch=86, lrate=0.042, error=4545.456
>epoch=87, lrate=0.039, error=4512.654
>epoch=88, lrate=0.036, error=4520.708
>epoch=89, lrate=0.033, error=4503.304
>epoch=90, lrate=0.030, error=4488.644
>epoch=91, lrate=0.027, error=4466.903
>epoch=92, lrate=0.024, error=4450.489
>epoch=93, lrate=0.021, error=4436.561
>epoch=94, lrate=0.018, error=4453.356
>epoch=95, lrate=0.015, error=4438.315
>epoch=96, lrate=0.012, error=4424.606
>epoch=97, lrate=0.009, error=4411.187
>epoch=98, lrate=0.006, error=4397.191
>epoch=99, lrate=0.003, error=4383.958

In [14]:
X = reduced_data.loc[:, reduced_data.columns != 'Class']
y = reduced_data.loc[:, reduced_data.columns == 'Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.349, random_state=1)

In [15]:
reduced_data.head()

,Clump_Thickness,Uniformity_of_Cell_Size,Uniformity_of_Cell_Shape,Marginal_Adhesion,Single_Epithelial_Cell_Size,Bare_Nuclei,Bland_Chromatin,Normal_Nucleoli,Mitoses,Class
0,5.000000,1.000000,1.00000,1.000000,3.000000,8.000000,2.000000,2.000000,1.0,Malignant
1,6.113859,1.856281,3.42814,0.772283,4.541999,3.374003,4.029861,9.799577,1.0,Malignant
2,6.000000,3.000000,0.70300,1.000000,3.000000,4.000000,0.109000,1.000000,1.0,Benign
3,1.000000,1.000000,3.00000,10.000000,3.000000,1.000000,1.000000,2.000000,1.0,Malignant
4,1.000000,1.000000,6.00000,2.000000,3.000000,1.000000,1.000000,1.000000,1.0,Benign

In [16]:
n=5
knn = KNeighborsClassifier(n_neighbors=n)  # Fit the classifier to the data
knn.fit(X_train, np.ravel(y_train, order='C'))

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [17]:
y_pred = knn.predict(X_test)

from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
print("\nConfution Matrix: \n{}\n".format(confusion_matrix(y_test, y_pred)))
print("\nClassification Report: \n{}\n".format(classification_report(y_test, y_pred)))

Accuracy: 0.6285714285714286

Confution Matrix:
[[90 17]
 [48 20]]


Classification Report:
              precision    recall  f1-score   support

      Benign       0.65      0.84      0.73       107
   Malignant       0.54      0.29      0.38        68

    accuracy                           0.63       175
   macro avg       0.60      0.57      0.56       175
weighted avg       0.61      0.63      0.60       175